blank_issues_enabled: true
contact_links:
  - name: Security vulnerability
    url: https://github.com/katajakasa/SDL_kitchensink/blob/master/SECURITY.md
    about: Do not report security vulnerabilities as public issues -- see the security policy for how to report them privately.
